
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.int}

server:
  port: 8080

#ribbon:
#  eureka:
#    enabled: false
#
#use-service:
#  ribbon:
#    listOfServers: localhost:8081,localhost:8001

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
#  ignoredServices: '*'
  prefix: /api
  debug:
    request: true
  routes:
    user:
      path: /user/**
      serviceId: use-service
      stripPrefix: false
    login:
      path: /login/**
      serviceId: use-service
      stripPrefix: false
    verifications:
      path: verifications/**
      url: http://127.0.0.1:8081
      stripPrefix: false
    todos:
      path: /todos/**
      url: http://127.0.0.1:8082
      stripPrefix: false

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE