
#spring:
#  application:
#    name: gateway
#  cloud:
#    consul:
#      host: consul
#      port: 8500
#      discovery:
#        instance-id: ${spring.application.name}:${random.int}

server:
  port: 8080

ribbon:
  eureka:
    enabled: false

user-service:
  ribbon:
    listOfServers: 127.0.0.1:8081

todo-service:
  ribbon:
    listOfServers: 127.0.0.1:8082

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
#  ignoredServices: '*'
  prefix: /api
  debug:
    request: true
  routes:
    user:
      path: /user/**
      serviceId: user-service
      stripPrefix: false
    login:
      path: /login/**
      serviceId: user-service
      stripPrefix: false
    verifications:
      path: verifications/**
      url: user-service
      stripPrefix: false
    todos:
      path: /todos/**
      url: todo-service
      stripPrefix: false

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE